# Generated by Django 2.2.4 on 2020-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201118_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='heading',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set(),
        ),
    ]
